FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y tcpdump && \
    pip install --no-cache-dir cryptography

COPY server.py .
COPY entrypoint.sh .

ENTRYPOINT ["./entrypoint.sh"]